/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Project = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Portfolio = IDL.Record({
  'title' : IDL.Text,
  'projects' : IDL.Vec(Project),
  'owner' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
  'getPortfolioMetadata' : IDL.Func(
      [],
      [IDL.Record({ 'title' : IDL.Text, 'owner' : IDL.Text })],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Project = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const Portfolio = IDL.Record({
    'title' : IDL.Text,
    'projects' : IDL.Vec(Project),
    'owner' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
    'getPortfolioMetadata' : IDL.Func(
        [],
        [IDL.Record({ 'title' : IDL.Text, 'owner' : IDL.Text })],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };